# Site settings
title: jinslee.com # site title
description: >- # site description
  Personal site of Jin Lee, a software engineering professional based in southern California.
lang: en-US # default lang
timezone: America/Los_Angeles # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/neojin/jinslee.com # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Jin Lee # author name
  bio: >- # tell to the world
    Software engineering professional based in southern California.
  username: neojin # general username
  github: neojin # github username
  twitter: jinslee # twitter username
  instagram: jinslee80 # facebook username
  email:
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://jinslee.com"
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
